version: '2'
services:
  jungledisk:
    build: .
    image: jeffre/jungledisk
    container_name: jungledisk
    restart: always
    ports:
      - 127.0.0.1:5900:5900
      - 127.0.0.1:6080:6080
    volumes:
      - ./data:/jungledisk
    environment:
      - TZ=America/Phoenix
      - JD_VNC_PASSWORD=changeme
      - JD_UID=1000
      - JD_GID=1000